version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    image: nginx:1.13.10
    volumes:
      - .:/code # Mount your code, so nginx/phpcould see it
      - .docker/nginx/site.conf:/etc/nginx/conf.d/site.conf # Use custom virtual hosts
    ports:
      - 127.0.0.1:$LOCAL_NGINX_DEV_PORT:8000 # For development. Open in browser 127.0.0.1:8000
      - 127.0.0.1:$LOCAL_NGINX_PROD_PORT:80 # To simulate production. Open in browser 127.0.0.1:8888

  php.symfony:
    container_name: php.symfony
    build: .docker/php/
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    environment: # Passing to environment same configuration as in .env file
      - APP_ENV=$APP_ENV
      - APP_SECRET=$APP_SECRET
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - .:/code # Mount your code, so nginx/phpcould see it

  prod.php.symfony:
    container_name: prod.php.symfony
    build: .docker/php/
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    environment: # Production environment should not use parameters from .env, but get them via nginx/apache
      - APP_ENV=prod # bin/console use APP_ENV value from environment
    volumes:
      - .:/code # Mount your code, so nginx/phpcould see it

  mysql.symfony:
    container_name: mysql.symfony
    image: mysql:5.7.21
    environment: # During first run root user with is generated with this password
      - MYSQL_ROOT_PASSWORD=p9iijKcfgENjBWDYgSH7
    volumes:
      - .docker/mysql-data/:/var/lib/mysql
    ports:
      - 127.0.0.1:3307:3306 # Connect to it via -h127.0.0.1 --port=3307

  phpmyadmin:
    container_name: phpmyadmin.symfony
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql.symfony:db
    ports:
      - 127.0.0.1:32773:80
#      environment:
#        - MYSQL_USERNAME=$MYSQL_USERNAME
#        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

  frontend.symfony:
    container_name: frontend.symfony
    build: .docker/frontend/
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    volumes:
      - .:/code # Mount your code, so javaScript tools could see it
    ports:
      - "127.0.0.1:9500:9500"
    extra_hosts:
     - "symfony.local:0.0.0.0"

  selenium.symfony:
    container_name: selenium.symfony
    image: selenium/standalone-chrome-debug
    ports:
      - 127.0.0.1:4444:4444 # To debug selenium API
      - 127.0.0.1:5900:5900 # To connect via VNC
